export const conversionContent = {
  fa: {
    requestDemo: {
      title: "درخواست دمو بازارباز",
      subtitle:
        "چند دقیقه زمان بگذارید و نوع کسب‌وکار خود را برای ما بنویسید تا مناسب‌ترین سناریوی بازارباز را برای شما توضیح دهیم.",
      fields: {
        fullName: "نام و نام خانوادگی",
        businessName: "نام کسب‌وکار",
        businessType: "نوع کسب‌وکار",
        phone: "شماره تماس",
        city: "شهر",
        description: "توضیح کوتاه نیاز کسب‌وکار",
        preferredContactTime: "ترجیح زمان تماس",
        consent: "تأیید می‌کنم اطلاعات واردشده برای پیگیری درخواست دمو توسط تیم بازارباز استفاده شود.",
      },
      submit: "ثبت درخواست دمو",
      successTitle: "درخواست شما ثبت شد",
      successMessage:
        "تیم بازارباز در اسرعطPossible با شما تماس خواهد گرفت. در فاز فعلی، این درخواست به صورت پیش‌نمایش ثبت می‌شود و ذخیره‌سازی دائمی در base داده‌های تولید deferred است.",
      note: "در نسخه فعلی، این فرم به صورت پیش‌نمایش است و داده‌ها به صورت دائم ذخیره نمی‌شوند.",
    },
    contact: {
      title: "تماس با بازارباز",
      subtitle:
        "برای سوالات فنی، تجاری و همکاری با بازارباز می‌توانید از طریق راه‌های زیر ارتباط بگیرید.",
      suitableFor: "مناسب برای چه کسب‌وکارهایی؟",
      suitableItems: [
        "فروشگاه‌های آنلاین و فیزیکی",
        "رستوران‌ها، کافه‌ها و فودکورت‌ها",
        "داروخانه‌ها و مراکز سلامت",
        "مطب‌ها، کلینیک‌ها و مراکز درمانی",
        "سالن‌های زیبایی و آرایشی",
        "مراکز آموزشی وtraining",
        "خدمات فنی و تعمیراتی",
        "سازمان‌های خدماتی و مشاوره‌ای",
      ],
      onboardingPath: "مسیر پیشنهادی راه‌اندازی",
      onboardingSteps: [
        "ثبت درخواست دمو از طریق فرم زیر",
        "بررسی نیازهای کسب‌وکار توسط تیم بازارباز",
        "راه‌اندازی پلتفرم و پیکربندی اولیه",
        "آموزش تیم و استقرار کامل",
      ],
      prepareInfo: "اطلاعاتی که بهتر است قبل از تماس آماده کنید",
      prepareItems: [
        "لیست محصولات یا خدمات اصلی",
        "نقش‌های کاربری موردنیاز",
        "نیازهای توابع سنتی (نوبت‌دهی، سفارش، باشگاه مشتریان و ...)",
        "حجم تقریبی مشتریان",
      ],
      ctaRequestDemo: "ثبت درخواست دمو",
      ctaLogin: "ورود به داشبورد",
      noContactInfo: "برای ثبت درخواست، از فرم درخواست دمو استفاده کنید.",
    },
    pricing: {
      title: "تعرفه‌ها و بسته‌بندی",
      subtitle:
        "بازارباز بر اساس نیاز کسب‌وکار، نوع فعالیت، تعداد شعبه‌ها، حجم سفارش/نوبت، پیامک/اعلان و سطح پشتیبانی بسته‌بندی می‌شود.",
      packages: [
        {
          id: "starter",
          name: "شروع",
          target: "فروشگاه کوچک و کسب‌وکارهای تازه‌تاسیس",
          description: "برای کسب‌وکارهایی که می‌خواهند حضور آنلاین خود را شروع کنند.",
          capabilities: [
            "صفحه اختصاصی کسب‌وکار",
            "مدیریت محصول یا سرویس",
            "سفارش‌گیری یا نوبت‌دهی آنلاین",
            "باشگاه مشتریان پایه",
            "گزارش‌های اولیه",
            "پشتیبانی ایمیلی",
          ],
        },
        {
          id: "growth",
          name: "رشد",
          target: "کسب‌وکارهای در حال رشد با نیاز به ابزارهای یکپارچه",
          description: "برای کسب‌وکارهایی که نیاز به مدیریت مشتری، کمپین و گزارش‌گیری دارند.",
          capabilities: [
            "همه قابلیت‌های بسته شروع",
            "کمپین‌ها، کوپن‌ها و تخفیف‌ها",
            "پیامک و اعلان مرورگر",
            "باشگاه مشتریان پیشرفته",
            "گزارش‌های تحلیلی",
            "پشتیبانی تلفنی و ایمیلی",
          ],
        },
        {
          id: "professional",
          name: "حرفه‌ای",
          target: "کسب‌وکارهای ثابت با حجم مشتری بالا",
          description: "برای کسب‌وکارهایی که نیاز به مدیریت کارکنان، چند شعبه و گزارش‌های کامل دارند.",
          capabilities: [
            "همه قابلیت‌های بسته رشد",
            "مدیریت کارکنان و دسترسی‌ها",
            "چند شعبه و چند کاربر",
            "API و یکپارچگی سفارشی",
            "گزارش‌های سفارشی",
            "پشتیبانی اولویت‌دار",
          ],
        },
        {
          id: "enterprise",
          name: "سازمانی / چندشعبه‌ای",
          target: "شبکه‌های franchise و سازمان‌های بزرگ",
          description: "برای سازمان‌هایی که نیاز به مدیریت متمرکز، امنیت اضافی و پشتیبانی اختصاصی دارند.",
          capabilities: [
            "همه قابلیت‌های بسته حرفه‌ای",
            "مدیریت متمرکز چند شعبه",
            "SSO و امنیت پیشرفته",
            "گزارش‌های سازمانی",
            "مشاوره اختصاصی",
            "SLA پشتیبانی",
          ],
        },
      ],
      note: "تعرفه‌ها نهایی نیست و بر اساس نیاز کاربران قابل سفارشی‌سازی است.",
      ctaRequestDemo: "درخواست دمو",
      ctaConsultation: "مشاوره برای انتخاب بسته",
    },
  },
  en: {
    requestDemo: {
      title: "Request a Bazar Baz Demo",
      subtitle:
        "Take a few minutes to tell us about your business so we can explain the most suitable Bazar Baz scenario for you.",
      fields: {
        fullName: "Full name",
        businessName: "Business name",
        businessType: "Business type",
        phone: "Phone number",
        city: "City",
        description: "Short description of your needs",
        preferredContactTime: "Preferred contact time",
        consent: "I confirm that the entered information will be used by the Bazar Baz team to follow up on the demo request.",
      },
      submit: "Submit demo request",
      successTitle: "Request submitted",
      successMessage:
        "The Bazar Baz team will contact you as soon as possible. In the current version, this request is submitted as a preview and permanent storage in the production database is deferred.",
      note: "In the current version, this form is a preview and data is not permanently stored.",
    },
    contact: {
      title: "Contact Bazar Baz",
      subtitle:
        "For technical, business, and partnership questions, you can reach us through the channels below.",
      suitableFor: "Suitable for which businesses?",
      suitableItems: [
        "Online and physical stores",
        "Restaurants, cafes, and food courts",
        "Pharmacies and health centers",
        "Clinics and medical centers",
        "Beauty salons",
        "Educational centers",
        "Technical and repair services",
        "Service and consulting organizations",
      ],
      onboardingPath: "Recommended onboarding path",
      onboardingSteps: [
        "Submit a demo request via the form below",
        "Bazar Baz team reviews business needs",
        "Platform setup and initial configuration",
        "Team training and full deployment",
      ],
      prepareInfo: "Information to prepare before contact",
      prepareItems: [
        "List of main products or services",
        "Required user roles",
        "Traditional function needs (appointments, orders, customer club, etc.)",
        "Approximate customer volume",
      ],
      ctaRequestDemo: "Submit demo request",
      ctaLogin: "Login to dashboard",
      noContactInfo: "To submit a request, use the request demo form.",
    },
    pricing: {
      title: "Pricing and Packages",
      subtitle:
        "Bazar Baz can be packaged based on business needs, service types, branch count, order/appointment volume, SMS/notification volume, and support level.",
      packages: [
        {
          id: "starter",
          name: "Starter",
          target: "Small shops and newly established businesses",
          description: "For businesses that want to start their online presence.",
          capabilities: [
            "Dedicated business page",
            "Product or service management",
            "Online ordering or appointment booking",
            "Basic customer club",
            "Basic reports",
            "Email support",
          ],
        },
        {
          id: "growth",
          name: "Growth",
          target: "Growing businesses needing integrated tools",
          description: "For businesses that need customer management, campaigns, and reporting.",
          capabilities: [
            "All Starter features",
            "Campaigns, coupons, and discounts",
            "SMS and browser notifications",
            "Advanced customer club",
            "Analytics reports",
            "Phone and email support",
          ],
        },
        {
          id: "professional",
          name: "Professional",
          target: "Established businesses with high customer volume",
          description: "For businesses that need staff management, multi-branch support, and complete reporting.",
          capabilities: [
            "All Growth features",
            "Staff management and access control",
            "Multi-branch and multi-user",
            "API and custom integration",
            "Custom reports",
            "Priority support",
          ],
        },
        {
          id: "enterprise",
          name: "Enterprise / Multi-Branch",
          target: "Franchise networks and large organizations",
          description: "For organizations needing centralized management, advanced security, and dedicated support.",
          capabilities: [
            "All Professional features",
            "Centralized multi-branch management",
            "SSO and advanced security",
            "Organizational reports",
            "Dedicated consulting",
            "Support SLA",
          ],
        },
      ],
      note: "Pricing is not final and can be customized based on user needs.",
      ctaRequestDemo: "Request demo",
      ctaConsultation: "Consultation for package selection",
    },
  },
  ar: {
    requestDemo: {
      title: "طلب عرض تجريبي من بازارباز",
      subtitle:
        "dedicate بضع دقائق و اكتب لنا عن عملك لنشرح لك السيناريو الأنسب من بازارباز.",
      fields: {
        fullName: "الاسم الكامل",
        businessName: "اسم العمل",
        businessType: "نوع العمل",
        phone: "رقم الهاتف",
        city: "المدينة",
        description: "وصف مختصر للاحتياجات",
        preferredContactTime: "وقت التواصل المفضل",
        consent: "أؤكد أن المعلومات المدخلة ستستخدم من قبل فريق بازارباز لمتابعة طلب العرض التجريبي.",
      },
      submit: "إرسال طلب العرض التجريبي",
      successTitle: "تم إرسال الطلب",
      successMessage:
        "سيتواصل فريق بازarbij denganك في أقرب وقت. في الإصدار الحالي، هذا الطلب مسبق ولا يتم التخزين الدائم في قاعدة بيانات الإنتاج.",
      note: "في الإصدار الحالي، هذا النموذج تجريبي ولا يتم تخزين البيانات بشكل دائم.",
    },
    contact: {
      title: "اتصل ببازارباز",
      subtitle:
        "للأسئلة التقنية والتجارية والشراكة، يمكنك التواصل عبر القنوات أدناه.",
      suitableFor: "مناسب لأي عمل؟",
      suitableItems: [
        "المتاجر عبر الإنترنت والفعلية",
        "المطاعم والمقاهي ومراكز الطعام",
        "الصيدليات ومراكز الصحة",
        "العيادات والمراكز الطبية",
        "صالونات التجميل",
        "المراكز التعليمية",
        "الخدمات الفنية والإصلاحية",
        "المنظمات الخدماتية والاستشارية",
      ],
      onboardingPath: "مسار الإعداد المقترح",
      onboardingSteps: [
        "إرسال طلب عرض تجريبي عبر النموذج أدناه",
        "مراجعة احتياجات العمل من فريق بازarbij",
        "إعداد المنصة والتكوين الأولي",
        "تدريب الفريق والنشر الكامل",
      ],
      prepareInfo: "معلومات يجب تحضيرها قبل الاتصال",
      prepareItems: [
        "قائمة المنتجات أو الخدمات الرئيسية",
        "الأدوار المطلوبة",
        "الاحتياجات الوظيفية (المواعيد، الطلبات، نادي العملاء، إلخ)",
        "حجم العملاء التقريبي",
      ],
      ctaRequestDemo: "إرسال طلب عرض تجريبي",
      ctaLogin: "تسجيل الدخول إلى لوحة التحكم",
      noContactInfo: "لإرسال طلب، استخدم نموذج طلب العرض التجريبي.",
    },
    pricing: {
      title: "الأسعار والباقات",
      subtitle:
        "يمكن تغليف بازarbij بناء على احتياجات العمل، نوع النشاط، عدد الفروع، حجم الطلبات/المواعيد، الرسائل القصيرة/الإشعارات ومستوى الدعم.",
      packages: [
        {
          id: "starter",
          name: "البداية",
          target: "المتاجر الصغيرة والأعمال الناشئة",
          description: "للأعمال التي تريد بدء وجودها عبر الإنترنت.",
          capabilities: [
            "صفحة عمل مخصصة",
            "إدارة المنتج أو الخدمة",
            "طلبات عبر الإنترنت أو حجز مواعيد",
            "نادي عملاء أساسي",
            "تقارير أولية",
            "دعم عبر البريد الإلكتروني",
          ],
        },
        {
          id: "growth",
          name: "النمو",
          target: "الأعمال المتنامية التي تحتاج أدوات متكاملة",
          description: "للأعمال التي تحتاج إدارة عملاء وحملات وتقارير.",
          capabilities: [
            "جميع ميزات باقة البداية",
            "الحملات والقسائم والخصومات",
            "رسائل SMS وإشعارات المتصفح",
            "نادي عملاء متقدم",
            "تقارير تحليلية",
            "دعم هاتفي وبريد إلكتروني",
          ],
        },
        {
          id: "professional",
          name: "الاحترافي",
          target: "أعمال راسخة بحجم عملاء مرتفع",
          description: "للأعمال التي تحتاج إدارة موظفين ودعم فروع متعددة وتقارير كاملة.",
          capabilities: [
            "جميع ميزات باقة النمو",
            "إدارة الموظفين والتحكم في الوصول",
            "فروع متعددة ومستخدمين متعددين",
            "API وتكامل مخصص",
            "تقارير مخصصة",
            "دعم ذو أولوية",
          ],
        },
        {
          id: "enterprise",
          name: "المؤسسات / متعدد الفروع",
          target: "سلاسل الامتياز والمنظمات الكبيرة",
          description: "للمنظمات التي تحتاج إدارة مركزية وأمان متقدم ودعم مخصص.",
          capabilities: [
            "جميع ميزات باقة الاحترافي",
            "إدارة مركزية متعددة الفروع",
            "SSO وأمان متقدم",
            "تقارير مؤسسية",
            "استشارات مخصصة",
            "مستوى خدمة اتفاقية",
          ],
        },
      ],
      note: "الأسعار غير نهائية ويمكن تخصيصها بناء على احتياجات المستخدمين.",
      ctaRequestDemo: "طلب عرض تجريبي",
      ctaConsultation: "استشارة لاختيار الباقة",
    },
  },
}

export type ConversionContent = typeof conversionContent
