export const featurePagesContent = {
  fa: {
    features: {
      seo: {
        title: "امکانات بازارباز — پلتفرم مدیریت کسب‌وکار ایرانی",
        description:
          "امکانات کامل بازارباز: مدیریت فروشگاه، سفارش‌ها، خدمات، نوبت‌دهی، باشگاه مشتریان، پیامک، اعلان، کمپین و داشبورد مدیریتی.",
      },
      hero: {
        title: "امکانات بازارباز برای مدیریت آنلاین کسب‌وکار",
        subtitle:
          "بازارباز ابزارهای اصلی مدیریت فروش، خدمات، مشتریان و ارتباطات را در یک پنل فارسی و یکپارچه کنار هم قرار می‌دهد.",
      },
      cta: {
        primary: "درخواست دمو",
        secondary: "مشاهده نمونه‌ها",
        tertiary: "مشاهده داشبورد بازارباز",
      },
      groups: [
        {
          id: "shop-orders",
          title: "مدیریت فروشگاه و سفارش‌ها",
          what: "محصولات، قیمت‌گذاری، موجودی، سبد خرید، پرداخت و پیگیری سفارش از یک داشبورد.",
          who: "صاحب کسب‌وکار، مدیر فروش، انباردار",
          workflow: "تعریف محصول → تنظیم قیمت و موجودی → مشتری سفارش را ثبت می‌کند → پرداخت آنلاین → پیگیری وضعیت در داشبورد",
          dashboardValue: "دسترسی لحظه‌ای به سفارش‌های جدید، موجودی و گزارش فروش",
          customerFacingValue: "مشاهده محصولات، افزودن به سبد خرید، پرداخت و پیگیری سفارش",
        },
        {
          id: "services-appointments",
          title: "مدیریت خدمات و نوبت‌دهی",
          what: "تعریف خدمات، کارکنان، ساعات کاری و مدیریت نوبت‌های مشتریان به صورت آنلاین.",
          who: "صاحب کسب‌وکار، مدیر خدمات، کارکنان",
          workflow: "تعریف خدمت و مدت زمان → تنظیم تقویم کارکنان → مشتری نوبت را انتخاب می‌کند → یادآوری خودکار → خدمات ارائه می‌شود",
          dashboardValue: "نمای کلی از برنامه هفتگی، نوبت‌های باز و عملکرد کارکنان",
          customerFacingValue: "مشاهده خدمات، انتخاب زمان مناسب و ثبت نوبت آنلاین",
        },
        {
          id: "customer-club",
          title: "باشگاه مشتریان و وفادارسازی",
          what: "دسته‌بندی مشتریان، اعطای کوپن، امتیاز وفاداری و کمپین‌های هدفمند.",
          who: "صاحب کسب‌وکار، مدیر بازاریابی",
          workflow: "عضویت مشتری در باشگاه → کسب امتیاز از خریدهای повтор → دریافت کوپن → engage مجدد با کمپین",
          dashboardValue: "گزارش میزان تعامل، تعداد عضو باشگاه و اثرگذاری کمپین‌ها",
          customerFacingValue: "دیدن امتیازات، استفاده از کوپن و اطلاع‌رسانی تخفیف‌های ویژه",
        },
        {
          id: "notifications",
          title: "پیامک، اعلان و اطلاع‌رسانی",
          what: "ارسال پیامک تراکنش‌محور، اعلان مرورگر و push notification برای مشتریان.",
          who: "صاحب کسب‌وکار، اپراتورdashboard",
          workflow: "سفارش ثبت می‌شود → سیستم پیامک یادآوری ارسال می‌کند → اعلان مرورگر نمایش داده می‌شود → مشتری از طریق کانال ترجیحی اطلاع می‌یابد",
          dashboardValue: "گزارش تحویل و خواندن پیام، مدیریت ترجیحات اعلان مشتری",
          customerFacingValue: "دریافت پیامک و اعلان در گوشی یا مرورگر برای سفارش، نوبت و تخفیف",
        },
        {
          id: "campaigns",
          title: "کمپین‌ها، تخفیف‌ها و پیشنهادهای ویژه",
          what: "ایجاد کمپین‌های تبلیغاتی، ارسال تخفیف‌های گروهی و پیگیری نتیجه.",
          who: "صاحب کسب‌وکار، مدیر بازاریابی",
          workflow: "طراحی کمپین → انتخاب گروه مشتری هدف → ارسال کوپن/اعلان → پیگیری نرخ باز شدن و فروش",
          dashboardValue: "داداش CRM کمپین، نرخ باز شدن و بازده مالی کمپین",
          customerFacingValue: "دریافت پیشنهادات ویژه، کوپن‌های تخفیف و اطلاع‌رسانی campagne",
        },
        {
          id: "dashboard",
          title: "داشبورد مدیریتی و گزارش‌ها",
          what: "نمای کلی از عملکرد کسب‌وکار، گزارش‌های فروش، خدمات، مشتریان و درآمد.",
          who: "صاحب کسب‌وکار، مدیرعامل، ناظر مالی",
          workflow: "ورود به داشبورد → مشاهده گزارش روزانه/هفتگی/ماهانه → خروجی CSV/Excel → تصمیم‌گیری برای بهبود کسب‌وکار",
          dashboardValue: "تصمیم‌گیری data-driven با نمودارهای interactive و گزارش‌های سفارشی",
          customerFacingValue: "بهبود مستمر خدمات و پیشنهادات بر اساس داده‌های واقعی کسب‌وکار",
        },
        {
          id: "business-page",
          title: "صفحه اختصاصی کسب‌وکار",
          what: "آدرس اختصاصی برای کسب‌وکار شما با قابلیت سفارش، نوبت‌دهی و نماد برند.",
          who: "صاحب کسب‌وکار، مدیر برند",
          workflow: "ثبت‌نام کسب‌وکار → دریافت آدرس اختصاصی → سفارشی‌سازی با لوگو و رنگ برند → فعال‌سازی فروشگاه یا نوبت‌دهی",
          dashboardValue: "مدیریت کامل محتوا، تصاویر و تنظیمات صفحه اختصاصی از یک جا",
          customerFacingValue: "دیدن کسب‌وکار به صورت حرفه‌ای با آدرس memorable و تجربه خرید/رزرو روان",
        },
        {
          id: "staff-roles",
          title: "مدیریت کارکنان و دسترسی‌ها",
          what: "تعریف نقش‌های کاری، محدودیت دسترسی و مدیریت تیم.",
          who: "صاحب کسب‌وکار، مدیر منابع انسانی، سرپرست",
          workflow: " دعوت کارکنان → تعریف نقش (ادمین، مدیر، کارمند) → اختصاص دسترسی → ثبت فعالیت و بررسی عملکرد",
          dashboardValue: "امنیت و کنترل دسترسی، Accountability کاری، گزارش عملکرد تیم",
          customerFacingValue: "خدماساز و کارکنان مجاز فقط به داده‌های مربوط به کار خود دسترسی دارند",
        },
        {
          id: "multilingual",
          title: "چندزبانه، فارسی‌محور و راست‌چین",
          what: "پلتفرم به فارسی طراحی شده و از زبان‌های دیگر پشتیبانی می‌کند.",
          who: "توسعه‌دهنده کسب‌وکار، مدیر محتوا",
          workflow: "انتخاب زبان‌های فعال (فارسی، انگلیسی، عربی) → سفارشی‌سازی متن‌ها → داشبورد و صفحه عمومی به همه زبان‌ها نمایش داده می‌شود",
          dashboardValue: "مدیریت محتوا در چند زبان بدون نیاز به کدنویسی اضافی",
          customerFacingValue: "تجربه کاربری روان به زبان مادری مشتری",
        },
      ],
    },
    dashboardShowcase: {
      seo: {
        title: "داشبورد مدیریتی بازارباز — پنل مدیریت کسب‌وکار",
        description:
          "داشبورد بازارباز برای مدیریت سفارش‌ها، خدمات، مشتریان، باشگاه مشتریان، کمپین، پیامک و گزارش‌گیری کسب‌وکار شما.",
      },
      hero: {
        title: "داشبوردی برای مدیریت روزانه کسب‌وکار شما",
        subtitle:
          "همه ابزارهای مدیریت کسب‌وکار در یک پنل فارسی و یکپارچه: سفارش‌ها، نوبت‌ها، مشتریان، کمپین و گزارش‌گیری.",
      },
      overview: [
        "مدیریت محصولات و خدمات",
        "مدیریت سفارش‌ها و پرداخت‌ها",
        "مدیریت نوبت‌ها و برنامه هفتگی",
        "مدیریت مشتریان و باشگاه مشتریان",
        "مدیریت کمپین‌ها و کدهای تخفیف",
        "پیامک، اعلان مرورگر و اطلاع‌رسانی",
        "پیگیری تحویل و خواندن پیام‌ها",
        "گزارش‌گیری و تحلیل عملکرد",
        "مدیریت کارکنان و دسترسی‌ها",
        "تنظیمات کسب‌وکار",
      ],
      workflows: [
        {
          id: "orders",
          title: "سفارش‌ها و پرداخت‌ها",
          description: "مشاهده سفارش‌های جدید، به‌روزرسانی وضعیت، صدور فاکتور و پیگیری پرداخت‌ها.",
          icon: "📦",
        },
        {
          id: "appointments",
          title: "خدمات و نوبت‌ها",
          description: "مدیریت تقویم، تعریف زمان‌های خالی، مشاهده نوبت‌های آینده و تأیید درخواست‌ها.",
          icon: "📅",
        },
        {
          id: "customers",
          title: "مشتریان و باشگاه مشتریان",
          description: "دسته‌بندی مشتریان، مشاهده سوابق خرید، مدیریت امتیاز وفاداری و عضویت باشگاه.",
          icon: "👥",
        },
        {
          id: "campaigns",
          title: "کمپین‌ها و کدهای تخفیف",
          description: "ایجاد کمپین، تعریف کوپن، انتخاب گروه هدف و پیگیری نتیجه.",
          icon: "🎯",
        },
        {
          id: "notifications",
          title: "پیامک و اعلان‌ها",
          description: "بررسی تنظیمات پیامک و اعلان، مشاهده گزارش تحویل و مدیریت ترجیحات مشتریان.",
          icon: "🔔",
        },
        {
          id: "reports",
          title: "گزارش‌ها و عملیات روزانه",
          description: "گزارش فروش، درآمد، عملکرد کمپین، تحلیل مشتریان و خروجی CSV/Excel.",
          icon: "📊",
        },
        {
          id: "settings",
          title: "تنظیمات کسب‌وکار و دسترسی‌ها",
          description: "ویرایش اطلاعات کسب‌وکار، دعوت کارکنان، تعریف نقش‌ها و تنظیم امنیت.",
          icon: "⚙️",
        },
      ],
      safety: {
        title: "اطمینان و اعتماد",
        subtitle:
          "داشبورد بازارباز برای تیم کسب‌وکار شما طراحی شده و اطلاعات شما نزد شماست.",
        bullets: [
          "داده‌های مشتریان و کسب‌وکار شما متعلک به خودتان است و با کسب‌وکارهای دیگر به اشتراک گذاشته نمی‌شود.",
          "ارسال پیامک واقعی فقط با فعال‌سازی صریح شما انجام می‌شود و پیش‌فرض حالت آزمایشی است.",
          "دسترسی بر اساس نقش (ادمین، مدیر، کارمند) و هر کاربر فقط به داده‌های مجاز خود دسترسی دارد.",
          "داشبورد برای کارکنان و مدیریت کسب‌وکار شما است و برای عموم بازدیدکنندگان عمومی قابل دسترسی نیست.",
        ],
      },
      cta: {
        primary: "درخواست دمو",
        secondary: "مشاهده تعرفه‌ها",
        tertiary: "ورود به داشبورد",
      },
    },
  },
  en: {
    features: {
      seo: {
        title: "Bazar Baz Features — Iranian Business Management Platform",
        description:
          "Complete Bazar Baz capabilities: shop management, orders, services, appointments, customer club, SMS, notifications, campaigns, and management dashboard.",
      },
      hero: {
        title: "Bazar Baz capabilities for online business management",
        subtitle:
          "Bazar Baz brings core sales, service, customer, and communication tools together in one Persian dashboard.",
      },
      cta: {
        primary: "Request Demo",
        secondary: "View Demos",
        tertiary: "View Bazar Baz Dashboard",
      },
      groups: [
        {
          id: "shop-orders",
          title: "Shop and Order Management",
          what: "Products, pricing, inventory, cart, checkout, and order tracking from one dashboard.",
          who: "Business owner, sales manager, warehouse staff",
          workflow: "Define product → Set price and inventory → Customer places order → Online payment → Track status in dashboard",
          dashboardValue: "Real-time access to new orders, inventory, and sales reports",
          customerFacingValue: "Browse products, add to cart, checkout, and track orders",
        },
        {
          id: "services-appointments",
          title: "Service and Appointment Management",
          what: "Define services, staff, working hours, and manage customer appointments online.",
          who: "Business owner, service manager, staff",
          workflow: "Define service and duration → Set staff calendar → Customer selects time slot → Auto-reminder → Service delivered",
          dashboardValue: "Weekly overview of schedule, open appointments, and staff performance",
          customerFacingValue: "View services, select time, and book appointment online",
        },
        {
          id: "customer-club",
          title: "Customer Club and Loyalty",
          what: "Customer segmentation, coupon distribution, loyalty points, and targeted campaigns.",
          who: "Business owner, marketing manager",
          workflow: "Customer joins club → Earn points from repeat purchases → Receive coupons → Re-engage with campaigns",
          dashboardValue: "Engagement reports, membership count, and campaign ROI",
          customerFacingValue: "View points, use coupons, and receive special offers",
        },
        {
          id: "notifications",
          title: "SMS, Notifications, and Alerts",
          what: "Send transactional SMS, browser notifications, and push notifications to customers.",
          who: "Business owner, dashboard operator",
          workflow: "Order placed → System sends reminder SMS → Browser notification shown → Customer receives preferred channel",
          dashboardValue: "Delivery and read reports, customer notification preference management",
          customerFacingValue: "Receive SMS and browser notifications for orders, appointments, and discounts",
        },
        {
          id: "campaigns",
          title: "Campaigns, Discounts, and Special Offers",
          what: "Create advertising campaigns, send group discounts, and track results.",
          who: "Business owner, marketing manager",
          workflow: "Design campaign → Select target customer group → Send coupon/notification → Track open rate and sales",
          dashboardValue: "Campaign CRM, open rates, and financial ROI",
          customerFacingValue: "Receive special offers, discount coupons, and campaign notifications",
        },
        {
          id: "dashboard",
          title: "Management Dashboard and Reports",
          what: "Overview of business performance, sales reports, services, customers, and revenue.",
          who: "Business owner, CEO, financial observer",
          workflow: "Login to dashboard → View daily/weekly/monthly reports → Export CSV/Excel → Make business decisions",
          dashboardValue: "Data-driven decision making with interactive charts and custom reports",
          customerFacingValue: "Continuous service improvement based on real business data",
        },
        {
          id: "business-page",
          title: "Dedicated Business Page",
          what: "Exclusive address for your business with ordering, booking, and brand identity.",
          who: "Business owner, brand manager",
          workflow: "Register business → Get dedicated address → Customize with logo and brand colors → Activate shop or booking",
          dashboardValue: "Full content, image, and settings management from one place",
          customerFacingValue: "Professional business presence with memorable address and smooth ordering/booking experience",
        },
        {
          id: "staff-roles",
          title: "Staff and Access Management",
          what: "Define job roles, access restrictions, and team management.",
          who: "Business owner, HR manager, supervisor",
          workflow: "Invite staff → Define role (admin, manager, employee) → Assign permissions → Track activity and performance",
          dashboardValue: "Security, access control, accountability, and team performance reports",
          customerFacingValue: "Service staff only access data relevant to their work",
        },
        {
          id: "multilingual",
          title: "Multilingual, Persian-First, RTL",
          what: "Platform designed in Persian with support for other languages.",
          who: "Business developer, content manager",
          workflow: "Select active languages (Persian, English, Arabic) → Customize texts → Dashboard and public pages display in all languages",
          dashboardValue: "Manage content in multiple languages without additional coding",
          customerFacingValue: "Smooth user experience in customer's native language",
        },
      ],
    },
    dashboardShowcase: {
      seo: {
        title: "Bazar Baz Dashboard — Business Management Panel",
        description:
          "Bazar Baz dashboard for managing orders, services, customers, customer club, campaigns, SMS, and business reporting.",
      },
      hero: {
        title: "A dashboard for your daily business management",
        subtitle:
          "All business management tools in one Persian dashboard: orders, appointments, customers, campaigns, and reporting.",
      },
      overview: [
        "Product and service management",
        "Order and payment management",
        "Appointment and calendar management",
        "Customer and customer club management",
        "Campaign and coupon management",
        "SMS, browser notifications, and alerts",
        "Delivery and read tracking",
        "Reporting and performance analysis",
        "Staff and access management",
        "Business settings",
      ],
      workflows: [
        {
          id: "orders",
          title: "Orders and Payments",
          description: "View new orders, update status, issue invoices, and track payments.",
          icon: "📦",
        },
        {
          id: "appointments",
          title: "Services and Appointments",
          description: "Manage calendar, set available slots, view upcoming appointments, and approve requests.",
          icon: "📅",
        },
        {
          id: "customers",
          title: "Customers and Customer Club",
          description: "Segment customers, view purchase history, manage loyalty points, and handle memberships.",
          icon: "👥",
        },
        {
          id: "campaigns",
          title: "Campaigns and Coupons",
          description: "Create campaigns, define coupons, select target audiences, and track results.",
          icon: "🎯",
        },
        {
          id: "notifications",
          title: "SMS and Notifications",
          description: "Check SMS and notification settings, view delivery reports, and manage customer preferences.",
          icon: "🔔",
        },
        {
          id: "reports",
          title: "Reports and Daily Operations",
          description: "Sales reports, revenue, campaign performance, customer analytics, and CSV/Excel exports.",
          icon: "📊",
        },
        {
          id: "settings",
          title: "Business Settings and Access",
          description: "Edit business information, invite staff, define roles, and configure security.",
          icon: "⚙️",
        },
      ],
      safety: {
        title: "Safety and Trust",
        subtitle:
          "The Bazar Baz dashboard is designed for your business team, and your data stays with you.",
        bullets: [
          "Your customer and business data belongs to you and is never shared with other businesses.",
          "Real SMS sending only happens with your explicit activation; the default is a safe trial mode.",
          "Access is role-based: admins, managers, and staff see only the data relevant to their role.",
          "The dashboard is for your internal team and is not accessible to the general public.",
        ],
      },
      cta: {
        primary: "Request Demo",
        secondary: "View Pricing",
        tertiary: "Login to Dashboard",
      },
    },
  },
  ar: {
    features: {
      seo: {
        title: "ميزات بازarbijAZ — منصة إدارة الأعمال الإيرانية",
        description:
          "ميزات بازarbijAZ الكاملة: إدارة المتجر، الطلبات، الخدمات، المواعيد، نادي العملاء، الرسائل القصيرة، الإشعارات، الحملات ولوحة التحكم.",
      },
      hero: {
        title: "ميزات بازarbijAZ لإدارة الأعمال عبر الإنترنت",
        subtitle:
          "يجمع بازarbijAZ أدوات إدارة المبيعات والخدمات والعملاء والاتصالات في لوحة تحكم عربية واحدة.",
      },
      cta: {
        primary: "طلب عرض تجريبي",
        secondary: "عرض النماذج",
        tertiary: "عرض لوحة تحكم بازarbijAZ",
      },
      groups: [
        {
          id: "shop-orders",
          title: "إدارة المتجر والطلبات",
          what: "المنتجات والتسعير والمخزون وسلة التسوق والدفع وتتبع الطلب من لوحة تحكم واحدة.",
          who: "صاحب العمل، مدير المبيعات، موظف المخزن",
          workflow: "تعريف المنتج → تحديد السعر والمخزون → العميل يضع الطلب → الدفع عبر الإنترنت → تتبع الحالة في لوحة التحكم",
          dashboardValue: "وصول فوري إلى الطلبات الجديدة والمخزون وتقارير المبيعات",
          customerFacingValue: "تصفح المنتجات، الإضافة إلى سلة التسوق، الدفع وتتبع الطلب",
        },
        {
          id: "services-appointments",
          title: "إدارة الخدمات والمواعيد",
          what: "تعريف الخدمات والموظفين وساعات العمل وإدارة مواعيد العملاء عبر الإنترنت.",
          who: "صاحب العمل، مدير الخدمات، الموظفون",
          workflow: "تعريف الخدمة والمدة → ضبط تقويم الموظفين → العميل يختار الوقت → تذكير تلقائي → تقديم الخدمة",
          dashboardValue: "نظر عام أسبوعي على الجدول والمواعيد المفتوحة وأداء الموظفين",
          customerFacingValue: "عرض الخدمات، اختيار الوقت المناسب وحجز الموعد عبر الإنترنت",
        },
        {
          id: "customer-club",
          title: "نادي العملاء والولاء",
          what: "تجزئة العملاء وتوزيع القسائم ونقاط الولاء والحملات المستهدفة.",
          who: "صاحب العمل، مدير التسويق",
          workflow: "العميل ينضم للنادي → يكسب نقاط من المشتريات المتكررة → يستلم قسائم → إعادة التفاعل عبر الحملات",
          dashboardValue: "تقارير التفاعل وعدد الأعضاء وعائد الحملات",
          customerFacingValue: "عرض النقاط واستخدام القسائم واستلام العروض الخاصة",
        },
        {
          id: "notifications",
          title: "الرسائل القصيرة والإشعارات",
          what: "إرسال رسائل نصيةTransactional وإشعارات المتصفح ودفع الإعلام للعملاء.",
          who: "صاحب العمل، مشغل لوحة التحكم",
          workflow: "يتم تسجيل الطلب → النظام يرسل تذكير SMS → يظهر إشعار المتصفح → العميل يستلم القناة المفضلة",
          dashboardValue: "تقارير التسليم والقراءة وإدارة تفضيلات إعلام العميل",
          customerFacingValue: "استلام الرسائل النصية والإشعارات للطلب والمواعيد والخصومات",
        },
        {
          id: "campaigns",
          title: "الحملات والخصومات والعروض الخاصة",
          what: "إنشاء حملات إعلانية وإرسال خصومات جماعية وتتبع النتائج.",
          who: "صاحب العمل، مدير التسويق",
          workflow: "تصميم الحملة → اختيار مجموعة العملاء المستهدفة → إرسال القسيمة/الإشعار → تتبع معدل الفتح والمبيعات",
          dashboardValue: "إدارة علاقات العملاء للحملة ومعدل الفتح والعائد المالي",
          customerFacingValue: "استلام العروض الخاصة وقسائم الخصم وإعلام الحملات",
        },
        {
          id: "dashboard",
          title: "لوحة التحكم والتقارير",
          what: "نظرة عامة على أداء العمل وتقارير المبيعات والخدمات والعملاء والإيرادات.",
          who: "صاحب العمل، المدير العام، المراقب المالي",
          workflow: "تسجيل الدخول إلى لوحة التحكم → عرض التقارير اليومية/الأسبوعية/الشهرية → تصدير CSV/Excel → اتخاذ القرارات",
          dashboardValue: "اتخاذ القرارات القائمة على البيانات مع الرسوم البيانية التفاعلية والتقارير المخصصة",
          customerFacingValue: "تحسين مستمر للخدمات والعروض بناءً على بيانات العمل الحقيقية",
        },
        {
          id: "business-page",
          title: "الصفحة المخصصة للعمل",
          what: "عنوان حصري لعملك مع إمكانية الطلب والحجز وهوية العلامة التجارية.",
          who: "صاحب العمل، مدير العلامة التجارية",
          workflow: "تسجيل العمل → الحصول على عنوان مخصص → التخصيص بالشعار وألوان العلامة التجارية → تفعيل المتجر أو الحجز",
          dashboardValue: "إدارة كاملة للمحتوى والصور والإعدادات من مكان واحد",
          customerFacingValue: "رؤية احترافية للعمل مع عنوان سهل التذكر وتجربة طلب/حجز سلسة",
        },
        {
          id: "staff-roles",
          title: "إدارة الموظفين والصلاحيات",
          what: "تعريف الأدوار الوظيفية وتقييد الصلاحيات وإدارة الفريق.",
          who: "صاحب العمل، مدير الموارد البشرية، المشرف",
          workflow: "دعوة الموظفين → تعريف الدور (مدير، مشرف، موظف) → تعيين الصلاحيات → تتبع النشاط والأداء",
          dashboardValue: "الأمان والتحكم في الصلاحيات والمساءلة وتقارير أداء الفريق",
          customerFacingValue: "يستطيع موظفو الخدمة الوصول فقط إلى البيانات المتعلقة بعملهم",
        },
        {
          id: "multilingual",
          title: "متعدد اللغات، الأولى فارسية، من اليمين لليسار",
          what: "المنصة مصممة بالفارسية مع دعم لغات أخرى.",
          who: "مطور العمل، مدير المحتوى",
          workflow: "اختيار اللغات النشطة (فارسية، إنجليزية، عربية) → تخصيص النصوص → عرض لوحة التحكم والصفحات العامة بجميع اللغات",
          dashboardValue: "إدارة المحتوى بعدة لغات دون حاجة إلى برمجة إضافية",
          customerFacingValue: "تجربة مستخدم سلسة بلغة العميل الأم",
        },
      ],
    },
    dashboardShowcase: {
      seo: {
        title: "لوحة تحكم بازarbijAZ — لوحة إدارة الأعمال",
        description:
          "لوحة تحكم بازarbijAZ لإدارة الطلبات والخدمات والعملاء ونادي العملاء والحملات والرسائل القصيرة وتقارير العمل.",
      },
      hero: {
        title: "لوحة تحكم لإدارة عملك اليومية",
        subtitle:
          "جميع أدوات إدارة العمل في لوحة تحكم عربية واحدة: الطلبات والمواعيد والعملاء والحملات والتقارير.",
      },
      overview: [
        "إدارة المنتجات والخدمات",
        "إدارة الطلبات والمدفوعات",
        "إدارة المواعيد والتقويم",
        "إدارة العملاء ونادي العملاء",
        "إدارة الحملات وقسائم الخصم",
        "الرسائل القصيرة وإشعارات المتصفح",
        "تتبع التسليم والقراءة",
        "التقارير وتحليل الأداء",
        "إدارة الموظفين والصلاحيات",
        "إعدادات العمل",
      ],
      workflows: [
        {
          id: "orders",
          title: "الطلبات والمدفوعات",
          description: "عرض الطلبات الجديدة وتحديث الحالة وإصدار الفواتير وتتبع المدفوعات.",
          icon: "📦",
        },
        {
          id: "appointments",
          title: "الخدمات والمواعيد",
          description: "إدارة التقويم وتعيين الأوقات المتاحة وعرض المواعيد القادمة والموافقة على الطلبات.",
          icon: "📅",
        },
        {
          id: "customers",
          title: "العملاء ونادي العملاء",
          description: "تجزئة العملاء وعرض سجل المشتريات وإدارة نقاط الولاء والعضويات.",
          icon: "👥",
        },
        {
          id: "campaigns",
          title: "الحملات وقسائم الخصم",
          description: "إنشاء الحملات وتحديد القسائم واختيار الجمهور المستهدف وتتبع النتائج.",
          icon: "🎯",
        },
        {
          id: "notifications",
          title: "الرسائل القصيرة والإشعارات",
          description: "التحقق من إعدادات الرسائل والإشعارات وعرض تقارير التسليم وإدارة تفضيلات العملاء.",
          icon: "🔔",
        },
        {
          id: "reports",
          title: "التقارير والعمليات اليومية",
          description: "تقارير المبيعات والإيرادات وأداء الحملات وتحليل العملاء وتصدير CSV/Excel.",
          icon: "📊",
        },
        {
          id: "settings",
          title: "إعدادات العمل والصلاحيات",
          description: "تعديل معلومات العمل ودعوة الموظفين وتحديد الأدوار وتكوين الأمان.",
          icon: "⚙️",
        },
      ],
      safety: {
        title: "السلامة والثقة",
        subtitle:
          "لوحة تحكم بازarbijAZ مصممة لفريق عملك وتظل بياناتك معك.",
        bullets: [
          "بيانات عملائك وعملك تنتمي إليك ولا تتم مشاركتها مع أعمال أخرى.",
          "إرسال الرسائل القصيرة الحقيقية يحدث فقط مع تفعيلك الصريح؛ الوضع الافتراضي هو وضع试验 الآمن.",
          "الصلاحيات based على الدور: يرى المدراء والموظفون فقط البيانات المتعلقة بعملهم.",
          "لوحة التحكم لفريق عملك الداخلي وليست متاحة للجمهور العام.",
        ],
      },
      cta: {
        primary: "طلب عرض تجريبي",
        secondary: "عرض الأسعار",
        tertiary: "تسجيل الدخول إلى لوحة التحكم",
      },
    },
  },
}

export type B2BFeaturePagesContent = typeof featurePagesContent
